# fly.toml app configuration file generated for pomo-2410 on 2024-10-15T02:10:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pomo-2410'
primary_region = 'nrt'

[build]
  image = 'mysql:8'

[http_service]
  internal_port = 3306
  force_https = true
  auto_stop_machines = true # コンテナをずっと稼働させたい時はここをfalseにする
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  
[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"
